# Generated by Django 4.2.1 on 2023-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_users_chat_id_alter_users_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
