# Generated by Django 4.2.1 on 2023-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_users_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='class_ruk',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='admin_verification',
            field=models.BooleanField(default=False),
        ),
    ]
