# Generated by Django 4.2.1 on 2023-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_students_evacuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuation',
            name='before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evacuation',
            name='missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='klass_room',
            field=models.CharField(max_length=30),
        ),
    ]
