# Generated by Django 4.2.1 on 2023-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_evacuation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='status',
            field=models.CharField(choices=[('2', 'забарикодированны'), ('0', 'нет данных'), ('1', 'эвакуированны')], default=0, max_length=2),
        ),
    ]
