# Generated by Django 4.2.1 on 2023-05-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_users_phone_number_alter_evacuation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuation',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Эвакуировано'),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='before',
            field=models.IntegerField(default=0, verbose_name='Должно быть'),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='klass_room',
            field=models.CharField(max_length=30, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='missing',
            field=models.IntegerField(default=0, verbose_name='Расхождение'),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='note',
            field=models.CharField(max_length=300, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='status',
            field=models.CharField(choices=[('1', 'эвакуированны'), ('0', 'нет данных'), ('2', 'забарикодированны')], default=0, max_length=2),
        ),
        migrations.CreateModel(
            name='missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(choices=[('б', 'болеет'), ('у', 'уважительная'), ('н', 'неуважительная')], default='н', max_length=2)),
                ('accuracy', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.students', verbose_name='Ученик')),
            ],
        ),
    ]
