# Generated by Django 4.2.1 on 2023-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_alter_evacuation_amount_alter_evacuation_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuation',
            name='status',
            field=models.CharField(choices=[('0', 'нет данных'), ('2', 'забарикодированы'), ('1', 'эвакуированы')], default=0, max_length=2),
        ),
    ]
