# Generated by Django 4.2.1 on 2023-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_alter_evacuation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuation',
            name='status',
            field=models.CharField(choices=[('1', 'эвакуированы'), ('0', 'нет данных'), ('2', 'забарикодированы')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='missing',
            name='accuracy',
            field=models.BooleanField(null=True),
        ),
    ]
